export const Data = [
    {
        title:"Dashboard",
        icon:' house',
        listItems:[
            {
                title:"home",
                route:'/'
            },
            {
                title:"about",
                route:'/about'
            },
            {
                title:"contact",
                route:'/contact'
            },
        ]
    },
    {
        title:"Applications",
        listItems:[
            {
                title:"item",
                route:'/'
            },
            {
                title:"item",
                route:'/'
            },
            {
                title:"item",
                route:'/'
            },
        ]
    },
    {
        title:"Ui elements",
        icon:" ",
        listItems:[
            {
                title:"item",
                route:'/'
            },
            {
                title:"item",
                route:'/'
            },
            {
                title:"item",
                route:'/'
            },
        ]
    },
]